### PR TITLE
cql_function_name_quote_comparison_fix

### PR DESCRIPTION
**Pull request by holmesie**
Fixed issue with observation function name check to make sure quotes are ignored

Test with: [Test111_v5_2_Artifacts.zip](https://github.com/projecttacoma/bonnie_bundler/files/1081295/Test111_v5_2_Artifacts.zip)

### CODE REVIEW

**Review by jbradl11 — APPROVED** [review]
Tested locally. Works.

**Comment by c-monkey** [comment]
I have not successfully found a function that is executed. I think observations, for example in https://oncprojectracking.healthit.gov/support/browse/BONNIE-272 are not executed. Didn't have a chance to finish debugging what's happening.

**Review by c-monkey — CHANGES_REQUESTED** [review]
Please show me the execution of a function. I tried with Test32v5 and couldn't get it to run.

**Review by c-monkey — APPROVED** [review]
As this fixes the load error and has nothing to do with observations not running, and Adam asserts we should be backwards compatible, it should be okay to release this.

**Pull request merged**
