### PR TITLE
cql4bonnie dependency updates

### PR DESCRIPTION
**Pull request by holmesie**
Updates to Bonnie dependencies. Ported from `master` to `cql4bonnie` to bring Gem versions up to date.

The Gemfile has been temporarily set to point to the corresponding branch in HDS, which is:
https://github.com/projectcypress/health-data-standards/tree/cql4bonnie_on_mongoid5_adam

The related PR in Bonnie is:
https://github.com/projecttacoma/bonnie/pull/864

---

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-897
- [x] Code diff has been done and been reviewed
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @hossenlopp
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree M/A

**Reviewer 2:**

Name: @mmayer
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Review by mayerm94 — DISMISSED** [review]
Regression works, JIRA tests have not be run on the most recent commit but they were run for the previous two. On the highly unlikely chance that there is a breaking change we will catch it when we test the full JIRA suite during staging deployment.

**Review by hossenlopp — CHANGES_REQUESTED** [review]
Unit tests fail on both travis and locally.

```
1) Failure:
MeasureDiffTest#test_loading_previous_against_updated [bonnie_bundler/test/unit/measure_diff_test.rb:60]:
Expected "Test 158" to not be equal to "Test 158".
```

**Review by mayerm94 — DISMISSED** [review]
Change makes sense, tested locally and everything works.

**Review by hossenlopp — APPROVED** [review]

**Review by hossenlopp — DISMISSED** [review]

**Review by mayerm94 — DISMISSED** [review]

**Review by hossenlopp — DISMISSED** [review]

**Review by hossenlopp — APPROVED** [review]
Travis issue fixed by effectively trying again. Tested with respective bonnie branch, passes.

**Review by mayerm94 — APPROVED** [review]
Ran tests locally.

**Pull request merged**
