### PR TITLE
CQL function name fix

### PR DESCRIPTION
**Pull request by holmesie**
Now adjusting function names in CQL in order to allow proper execution by the CQL execution engine in JavaScript.

To test, use:
[Test111_v5_2_Artifacts.zip](https://github.com/projecttacoma/bonnie_bundler/files/1058768/Test111_v5_2_Artifacts.zip)
[ED1_v5_2_Artifacts.zip](https://github.com/projecttacoma/bonnie_bundler/files/1058769/ED1_v5_2_Artifacts.zip)

### CODE REVIEW

**Review by mayerm94 — APPROVED** [review]
Tested locally, works

**Review by c-monkey — CHANGES_REQUESTED** [review]
Please add support for detecting name collisions introduced by space removal, e.g "Foo Bar" and "FooBar" becoming the same.

**Comment by mulcahyk** [comment]
I like the way that each step is commented.

**Review by jbradl11 — APPROVED** [review]
Works. Looks good.

**Comment by c-monkey** [comment]
I figured everyone tested the simple case (which I had as well and it worked fine) so I decided to go fancy. Here is the source CQL and measure as it appears in Bonnie, are we okay with this?

Screen grab from original .cql file:

screen shot 2017-06-12 at 2 33 35 pm


And a screen grab from in the Bonnie tool:

screen shot 2017-06-12 at 2 30 45 pm

It's not obvious to me how we got a space in one of the names...

**Comment by c-monkey** [comment]
@mayerm94 or @jbradl11 please one of you test this. Adam squashed and submitted new code, the checkboxes still say you indicate approval of this untested code.

Thanks.

**Review by c-monkey — APPROVED** [review]
Tested locally, looks good to me.

**Comment by mayerm94** [comment]
Tested locally again. Changes look good

**Pull request merged**
