### PR TITLE
Multi library test

### PR DESCRIPTION
**Pull request by alexanderelliott121**
Create test to ensure that multi-library cql measures have the appropriate data-structure.

### CODE REVIEW

**Review by lukoktonos — APPROVED** [review]
Looks good.  Test ran without errors.

**Review by hossenlopp — CHANGES_REQUESTED** [review]
Test does do the job. Only looks for existence and size of the `elm` field. I would be more comfortable if it also checked the names of the libraries loaded and the `cql_statement_dependencies` structure for sanity.

**Review by c-monkey — APPROVED** [review]
Test coverage and # tests increases.

**Comment by edeyoung** [comment]
Hoss verbally approved this.

**Pull request merged**
