### PR TITLE
update Gemfile.lock to match HDS update of nokogiri

### PR DESCRIPTION
**Pull request by hossenlopp**

### CODE REVIEW

**Review by holmesie — APPROVED** [review]
Changes are in line with the Gemfile lock changes being made to Bonnie. Tested and everything works. Approved.

**Comment by mayerm94** [comment]
What version of ruby did you test this with? @hossenlopp @holmesie

**Comment by hossenlopp** [comment]
2.3.4

**Review by mayerm94 — APPROVED** [review]
I had to install libv8 with --with-system-v8 in order to bundle install but that has nothing to do with this PR. Everything works as expected.

**Comment by edeyoung** [comment]
CI checks failing due to new version of mongo which doesn't like javascript functions passed in as a string. Not related to PR.

**Pull request merged**
